### ISSUE TITLE
/mentor

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/hatbot-discord#2]
criar um comando `/mentor` com um input com frontend ou backend com um autocomplete para esses dois e digitar uma duvida para marcar algum mentor da área responder, essa ideia precisa ser discutida porque precisa saber onde vai ficar as as duvidas, talvez uma canal com threads. é importante ser publico por causa do `learn in public`

**Comment by Sherlockzen** [comment]
Eu estou retornando pra essa task e minha ideia é a seguinte: Fazer o comando de forma que ele fique mais ou menos a prova de ter que alterar caso os cargos de mentores mudem, por exemplo se adcionar o **Devops - Mentor** o comando já se ajusta a isso porque ele pega a lista de cargos de mentor que tem no server. Ai seguindo isso teríamos a possibilidade de lançar uma dúvida pra qualquer mentor e marcar essa galera.

Acho que fica legal criar uma thread com a dúvida da pessoa lá no #help do community pq é bem geralzão, o que vocês acham? 

@k1nha @hxsggsz

**Comment by k1nha** [comment]
boaa, concordo
