### ISSUE TITLE
comando `/change` marcando pessoa errada

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/hatbot-discord#21]
aparentemente no comando `/change` as vezes o bot marca outra pessoa em vez de marcar quem abriu a thread, necessário corrigir isso 

<img width="339" alt="image" src="https://github.com/devhatt/hatbot-discord/assets/103784814/10ca0f8f-aa1b-4f56-8676-67ca661c26d9">

**Comment by aalmeida00** [comment]
eu quero!!!
