### ISSUE TITLE
sincronizar o chat da twitch pra enviar as mensagem no discord

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/hatbot-discord#22]
necessário criar um webhook pra enviar no canal de meting as mensagens enviada no chat.

**Comment by Alecell** [comment]
@hxsggsz e @k1nha isso aqui não ta feito já? Falta fazer deploy? Qual o status disso?

**Comment by k1nha** [comment]
tinha feito em go. Ainda não fiz a integração com o nosso bot, achei que seria mais simples rodar isso em um .exe já que só vai ser necessário durante as dailys
