### ISSUE TITLE
create a reminder to daily

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/hatbot-discord#8]
the bot have to mark everyone that have the role of the project with the meeting agenda 1 hour and 10 minutes before the meeting start

**Comment by k1nha** [comment]
Tenho algumas dúvidas, porque a notificação precisa ser 1h10min antes da daily? achei um horário meio quebrado, pensei algo entre 1h ou 30min antes
e qual seria a mensagem enviada?

**Comment by hxsggsz** [comment]
o horário não ta definido, mas a ideia é o bot avisar antes e quando tiver quase na hora com uma mensagem genérica tipo "falta tantos minutos pra daily começar" no chat geral de cada projeto

**Comment by k1nha** [comment]
Beleza, vou pegar essa issue pra fazer
pensei em adicionar os assuntos da daily na mensagem, mas dai precisaríamos ver como pegar essa info do notion

**Comment by Alecell** [comment]
@k1nha e @hxsggsz isso aqui não ta finalizado?

**Comment by k1nha** [comment]
Ainda não  foi 100%, o cron job tem alguns problemas (sincronia com feriados, eventos do discord, etc...) 
Estava estudando outra maneira de integrar usando Google Api
